services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/famcan-riskassessment/frontend:latest
    ports:
      - "5173:5173"
    container_name: risk-prediction-frontend
    restart: unless-stopped
    networks:
      - famcan-network

  nginx:
    container_name: nginx
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt/archive/famcan.org.ir:/etc/nginx/ssl:ro
    depends_on:
      - frontend
    restart: unless-stopped
    networks:
      - famcan-network

networks:
  famcan-network:
    external: true
